### PR TITLE
Make bind address configurable

### PR DESCRIPTION
**Pull request by eskimor**
Fix issue #7

### CODE REVIEW

**Comment by bltavares** [comment]
I would need to test those out on my env during the weekend, to ensure that Win <-> Linux <-> Mac still works as expected, but it looks promising

**Comment by eskimor** [comment]
Thanks, that would be awesome!

**Comment by bltavares** [comment]
That is looking good! I've tested on a software that use this lib and it keeps working (after some unrelated fixes on #11).

I'll merge and release a new version. Thanks!

**Comment by eskimor** [comment]
Awesome, thanks! :-)

**Pull request merged**
