### PR TITLE
Use now apparently maintained if-addrs

### PR DESCRIPTION
**Pull request by eskimor**
instead of unmaintained get-if-addrs.

### CODE REVIEW

**Comment by eskimor** [comment]
This PR depends on a new release of `if-addrs`.

**Comment by eskimor** [comment]
As far as I can see, all the build errors are already fixed on master of `if-addrs`, just waiting to be released.

**Comment by bltavares** [comment]
@eskimor I'm looking at the crate, and it does not seem to have any meaningful improvements over the fork. The last commits so far have been only renames of the crate from a few weeks ago.

I don't see any reason to change over to that dependency given it has no code change so far. I'd rather stay on a stable release until fixes/improvements appear on the fork.

**Comment by eskimor** [comment]
Fair enough :-) I was planning on integrating your reverse patch there, but I don't see a problem waiting until that actually happens ;-) One minor thing though worth mentioning: The fork already bumped the winapi dependency, so that could be useful already.

**Comment by bltavares** [comment]
Oh, adding the reverse there would be great! It seems to have some new activity there. I would consider moving to the fork to remove the hotfix on mips :+1:

**Comment by mon** [comment]
Bit of a necro, but I need support for link-local addresses, which the new if-addrs exposes as a feature. Can this PR be resurrected?

**Comment by mon** [comment]
There's actually some more code required as I have 3 link-local addresses on my machine, and two of them are *actually* disconnected and fail with `ErrorKind::AddrNotAvailable`. Worth just making my own PR with the new `if_addrs` and the other required handling for this case?

**Comment by bltavares** [comment]
Sure thing, I'd consider replacing the lib if the MIPS support have been merged, which was the blocker last time.

**Comment by mon** [comment]
Truthfully, I can't tell if they fixed the MIPS issue yet - do you have a MIPS system to test it on? I've never touched that arch.

**Comment by bltavares** [comment]
Yes, I do have some `mips` routers to test, and the [CI should](https://github.com/bltavares/multicast-socket/blob/master/.github/workflows/cross_compile.yml#L17) check for compilation at least.

**Comment by mon** [comment]
I looked a little more intently - the old MIPS bug is caused by a manual sockaddr parse:
https://github.com/maidsafe-archive/get_if_addrs/blob/master/src/sockaddr.rs#L37-L43

The new one uses `to_ne_bytes`, which will be big-endian aware:
https://github.com/messense/if-addrs/blob/master/src/sockaddr.rs#L42

I'll start work on the re-port :)

**Comment by bltavares** [comment]
Thanks for the interest @mon :) Let me know how it goes, and I can test on a device later

**Comment by bltavares** [comment]
Closed by #19

**Pull request closed without merging**
