### PR TITLE
Move to maintained `if-addrs` crate

### PR DESCRIPTION
**Pull request by mon**
Pro: mips should work now
Con: The mips pipeline no longer runs because of https://github.com/rust-lang/compiler-team/issues/648

Not really sure of the best action here...

I'll add the link-local stuff in another PR so there's a clear chain of commits.

### CODE REVIEW

**Comment by mon** [comment]
Thoughts on MIPS solutions:
- just use an older rustc instead of stable
- Wait until this is fixed: https://github.com/rust-lang/rust/issues/120655 and cross re-enables their MIPS targets, then add -`Zbuild-std` to the pipeline

Any thoughts? Not in a hurry to merge, I just remember it every now and then 😅

**Comment by bltavares** [comment]
Hey there! I'm not ignoring this PR, but my MIPS setup is completely broken, and it's been taking a while to update and fix due to upstream lack pre-compiled `libstd` now.

I really appreciate the update, and as soon as I have more time, and can actually fix my local setup, I'll be landing this change

**Comment by mon** [comment]
Excellent, thanks! Good luck fixing your local setup, I don't envy you...

**Comment by bltavares** [comment]
I've been able to validate the changes on Windows amd64, Linux amd64 and Linux MIPS :)

Thanks for the contribution!

**Comment by mon** [comment]
Excellent news, thanks! How'd you fix your MIPS setup in the end? Just using an older rustc, or did you massage std to compile?

**Pull request merged**
